### ISSUE TITLE
Create a pull request template

### ISSUE THREAD

**Issue by nickytonline** [nickytonline/edge-and-node-frontend-starter#2]
## Description

Create a pull request template. I would probably go with a subset of what is in the [Forem pull request template](https://github.com/forem/forem/blob/main/.github/PULL_REQUEST_TEMPLATE.md) for now. And it would definitely need to have the animated GIF section. 😎

The file has been created, but it's empty.

**Comment by mrsantons** [comment]
Can I be assigned?
